C:\Users\adham\Desktop\git\stroke-pain-app-1\backend> docker-compose down --volumes --remove-orphans
>> docker system prune --all --volumes -f
>> docker-compose build --no-cache
>> docker-compose up
time="2025-06-25T05:09:02+02:00" level=warning msg="C:\\Users\\adham\\Desktop\\git\\stroke-pain-app-1\\backend\\docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
services:
  backend:
    build: .
    container_name: stroke-pain-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
